# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 06:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleinfomation',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chields', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicleinfomation',
            name='amount',
            field=models.FloatField(default=0.0, verbose_name='Amount collected'),
        ),
    ]
