# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVehicleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=30)),
                ('vehicle_number', models.CharField(max_length=20)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='profile.FlatNumber')),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='leaving_type',
            field=models.CharField(choices=[('own', 'My Own Home'), ('rent', 'I am Leaving here rented'), ('pg', 'I am Leaving here paying guest')], max_length=40),
        ),
    ]
