# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 14:25
from __future__ import unicode_literals

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profile', '0002_auto_20170122_0623'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('details', models.CharField(max_length=20)),
                ('date', models.DateTimeField(verbose_name='Date of birth')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Event Image')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='leaving_type',
            field=models.CharField(choices=[('own', 'Home owner'), ('spouse', 'Wife'), ('son', 'Son'), ('daughter', 'Daughter'), ('father', 'Father'), ('mother', 'Mother'), ('faimily', 'My Faimily member'), ('rent', 'Rented Member')], max_length=40, verbose_name='Resident Type'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='permanent_address',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Permanent address. if have?'),
        ),
    ]
