# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 06:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0007_auto_20170121_0609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='user_info',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='profile.UserProfile'),
        ),
    ]
