# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0008_auto_20170121_0619'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleInfomation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=30)),
                ('vehicle_number', models.CharField(max_length=20)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='profile.FlatNumber')),
            ],
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='flat',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
